// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlakDukkaniDAL.Context;

#nullable disable

namespace PlakDukkaniDAL.Migrations
{
    [DbContext(typeof(PlakDukkaniDbContext))]
    partial class PlakDukkaniDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlakDukkaniDATA.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AlbumAdi")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("date")
                        .HasColumnName("CikisTarihi")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fiyat")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("date")
                        .HasColumnName("GuncellemeTarihi")
                        .HasColumnOrder(9);

                    b.Property<decimal?>("IndirimOrani")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("IndirimOrani")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("date")
                        .HasColumnName("KayitTarihi")
                        .HasColumnOrder(8);

                    b.Property<string>("Sanatci")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("SanatciAdi")
                        .HasColumnOrder(3);

                    b.Property<bool>("SatisDevamMi")
                        .HasColumnType("bit")
                        .HasColumnName("SatisAktifMi")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.ToTable("Albumler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Mançoloji",
                            CikisTarihi = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 250m,
                            IndirimOrani = 20m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9416),
                            Sanatci = "Barış Manço",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gülümse",
                            CikisTarihi = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 230m,
                            IndirimOrani = 0m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9432),
                            Sanatci = "Sezen Aksu",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Dil Yarası",
                            CikisTarihi = new DateTime(1975, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 200m,
                            IndirimOrani = 10m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9434),
                            Sanatci = "Orhan Gencebay",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ölürüm Sana",
                            CikisTarihi = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 280m,
                            IndirimOrani = 0m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9436),
                            Sanatci = "Tarkan",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 5,
                            Ad = "O",
                            CikisTarihi = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 210m,
                            IndirimOrani = 25m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9437),
                            Sanatci = "Teoman",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Ajda'97",
                            CikisTarihi = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 300m,
                            IndirimOrani = 25m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9438),
                            Sanatci = "Ajda Pekkan",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Mavi Mavi",
                            CikisTarihi = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 300m,
                            IndirimOrani = 0m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9439),
                            Sanatci = "İbrahim Tatlıses",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Gülümse (Yeşilçam Şarkıları)",
                            CikisTarihi = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 250m,
                            IndirimOrani = 0m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9440),
                            Sanatci = "Sezen Aksu",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Kenan Doğulu 2",
                            CikisTarihi = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 250m,
                            IndirimOrani = 10m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9442),
                            Sanatci = "Kenan Doğulu",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Sakla Samanı Gelir Zamanı",
                            CikisTarihi = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 210m,
                            IndirimOrani = 10m,
                            KayitTarihi = new DateTime(2023, 11, 9, 15, 17, 5, 433, DateTimeKind.Local).AddTicks(9443),
                            Sanatci = "Barış Manço",
                            SatisDevamMi = false
                        });
                });

            modelBuilder.Entity("PlakDukkaniDATA.Entities.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("KullaniciAdi")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("date")
                        .HasColumnName("GuncellemeTarihi")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("date")
                        .HasColumnName("KayitTarihi")
                        .HasColumnOrder(5);

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sifre")
                        .HasColumnOrder(3);

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Unvan")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
